version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dojo_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dojo_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dojo_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dojo_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      CORS_ORIGIN: http://localhost:5173
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dojo_app
      PGPORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  adminer:
    image: adminer:4
    container_name: dojo_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pgdata:
